<template>
  <div class="wrapper" ref="wrap">
    <ul class="content">
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
      <li>nhao</li>
    </ul>
  </div>
</template>

<script>
import BScroll from "better-scroll";
export default {
  name: "Category",
  data() {
    return {
      scroll: null,
    };
  },
  mounted() {
    this.scroll = new BScroll(this.$refs.wrap, {
      probeType: 3,
      pullUpLoad: true,
      click:true
    });
    this.scroll.on("scroll", (position) => {
      console.log(position);
    });
    this.scroll.on("pullingUp", () => {
      console.log("上拉加载更多");
    });
  },
  methods: {
    
  },
};
</script>

<style  scoped>
.wrapper {
  height: 200px;
  background-color: red;
}
</style>
